# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4122cf4e1853e2a51c40124951a14ac743d9131ce32bb007d4ca49f50147203296a4fb764053b7916a26c84b73dcd5df968eb46e5f08dbf645b0232349c30e86

test:
  secret_key_base: 9dbdf07d6d91dd571cd486b01b4b583e8b30df8fbb3372b29878e86b38475b6ad1186f17c4e233e26caa4986cdb49f5c2bfa534d91301e63f868199ba91be92f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
